#!/usr/bin/env Rscript
# Stacked PPOM-vs-POM median-effect Manhattans (short) for the 16 SPN penicillin
# minima-binning run. Four panels, top to bottom:
#   A  exp(|median beta|), PPOM  (4 cutpoints overlaid, plasma)
#   B  exp(|median beta|), POM   (single series, purple)
#   C  median beta,        PPOM  (4 cutpoints overlaid, plasma)
#   D  median beta,        POM   (single series, purple)
# PPOM effects come from its depruned_variant_effects.csv; POM effects come from
# the CSV regenerated by regen_pom_variant_effects.R. Styling matches the short
# overlay Manhattans in replot_ppom_overlay_manhattans_short.R.

suppressPackageStartupMessages({
  library(ggplot2)
  library(viridis)
  library(data.table)
  library(cowplot)
})

RESULTS  <- "/nfs/research/jlees/jacqueline/thesis_results"
PPOM_DIR <- file.path(RESULTS, "gwas_spn_penicillin/inference/16_spn_penicillin_MIC_minimabinning_PPOM")
POM_DIR  <- file.path(RESULTS, "gwas_spn_penicillin/inference/16_spn_penicillin_MIC_minimabinning_POM")
VARIANT_INDEX <- file.path(RESULTS, "gwas_datasets/inference/16_spn_penicillin_MIC_minimabinning/16_spn_penicillin_MIC_minimabinning_variant_index.csv")
OUT_DIR  <- file.path(RESULTS, "paper_figures", "manhattan_short")
OUT_PNG  <- file.path(OUT_DIR, "16_spn_penicillin_PPOM_POM_median_manhattans_short.png")

POM_COLOUR <- "#6A00A8"   # single-series purple, matching replot_rate_manhattan_short.R
BASE_SIZE  <- 14

# Genome coordinate per variant (column 2), in original variant-ID order. Shared
# by both runs (same dataset).
positions <- read.csv(VARIANT_INDEX)[, 2]
V <- length(positions)

# PPOM overlay frame: one row per (variant, cutpoint), median carried per cutpoint.
# Mirrors build_overlay_df() in replot_ppom_overlay_manhattans_short.R:75-96.
ppom <- data.table::fread(file.path(PPOM_DIR, "fitted_model", "depruned_variant_effects.csv"))
n_cutpoints <- length(unique(ppom$cutpoint))
stopifnot(nrow(ppom) == V * n_cutpoints)
has_mic <- !all(is.na(ppom$cutpoint_MIC))
ppom_df <- data.frame(
  pos      = rep(as.numeric(positions), times = n_cutpoints),
  median   = as.numeric(ppom$median),
  cutpoint = ppom$cutpoint
)
if (has_mic) {
  ppom_df$cutpoint_label <- as.character(ppom$cutpoint_MIC)
  legend_title <- expression(atop("breakpoint", (mu * "g" %.% "mL"^{-1})))
} else {
  ppom_df$cutpoint_label <- as.character(ppom$cutpoint)
  legend_title <- "cutpoint"
}
ppom_df$cutpoint_label <- factor(
  ppom_df$cutpoint_label,
  levels = unique(ppom_df$cutpoint_label[order(ppom_df$cutpoint)])
)

# POM single-series frame: one effect per variant.
pom <- data.table::fread(file.path(POM_DIR, "fitted_model", "depruned_variant_effects.csv"))
stopifnot(nrow(pom) == V)
pom_df <- data.frame(pos = as.numeric(positions), median = as.numeric(pom$median))

plasma_colors <- viridis::viridis(n_cutpoints + 1L, option = "plasma")[2:(n_cutpoints + 1L)]
base_theme <- ggplot2::theme_minimal(base_size = BASE_SIZE)

YLAB_MEDIAN  <- expression(tilde(beta))
YLAB_EXP_ABS <- expression("e"^{abs(tilde(beta))})

# PPOM panel: overlay cutpoints in plasma; colour legend suppressed (shared
# legend is added once at the bottom of the figure).
ppom_panel <- function(yexpr, ylab, show_x) {
  ggplot2::ggplot(ppom_df, ggplot2::aes(x = pos, y = !!yexpr, colour = cutpoint_label)) +
    ggplot2::geom_point(alpha = 0.4) +
    ggplot2::scale_colour_manual(values = plasma_colors, guide = "none") +
    ggplot2::ylab(ylab) +
    (if (show_x) ggplot2::xlab("genome coordinate (bp)") else ggplot2::xlab(NULL)) +
    base_theme
}

# POM panel: single purple series.
pom_panel <- function(yexpr, ylab, show_x) {
  ggplot2::ggplot(pom_df, ggplot2::aes(x = pos, y = !!yexpr)) +
    ggplot2::geom_point(alpha = 0.4, colour = POM_COLOUR) +
    ggplot2::ylab(ylab) +
    (if (show_x) ggplot2::xlab("genome coordinate (bp)") else ggplot2::xlab(NULL)) +
    base_theme
}

pA <- ppom_panel(quote(exp(abs(median))), YLAB_EXP_ABS, show_x = FALSE)
pB <- pom_panel (quote(exp(abs(median))), YLAB_EXP_ABS, show_x = FALSE)
pC <- ppom_panel(quote(median),           YLAB_MEDIAN,  show_x = FALSE)
pD <- pom_panel (quote(median),           YLAB_MEDIAN,  show_x = TRUE)

# Shared breakpoint legend (extracted from a PPOM panel shown with a bottom legend).
legend_src <- ggplot2::ggplot(ppom_df,
    ggplot2::aes(x = pos, y = median, colour = cutpoint_label)) +
  ggplot2::geom_point(alpha = 0.4) +
  ggplot2::scale_colour_manual(values = plasma_colors) +
  ggplot2::labs(colour = legend_title) +
  base_theme +
  ggplot2::theme(legend.position = "bottom") +
  ggplot2::guides(colour = ggplot2::guide_legend(
    nrow = 1, override.aes = list(alpha = 1, size = 3)))
shared_legend <- cowplot::get_legend(legend_src)

panels <- cowplot::plot_grid(
  pA, pB, pC, pD,
  ncol = 1, align = "v", axis = "lr",
  labels = c("A", "B", "C", "D"),
  label_fontface = "bold", label_size = 24
)
figure <- cowplot::plot_grid(panels, shared_legend, ncol = 1,
                             rel_heights = c(1, 0.05))

dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)
short_height <- 8 * 2 / 3
ggplot2::ggsave(OUT_PNG, plot = figure, width = 16,
                height = 4 * short_height + 1, dpi = 300, limitsize = FALSE)
message("Wrote ", OUT_PNG)
